authors = ["Josua Grawitter <josua.grawitter@campus.tu-berlin.de>"]
name = "Struve"
uuid = "bbbc800e-c7bf-11e8-107b-9b6d1d23829a"
version = "0.1.0"

[deps]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
